Update modułu i dodanie przypadków testowych.
bikol/PotegowanieCC-2017 pull request #5
Opened 2017-05-25 13:47 UTC by m1kra

2017-05-26 09:10 UTC, bikol requested changes
Proszę usunąć konfiguracje travisa z pull requesta.

2017-05-26 20:50 UTC, m1kra commented
Usunąłem travisa - nie wiedziałem, że nie powinienem go dodawać. Pull request jest znowu gotowy.

2017-05-29 09:24 UTC, bikol approved these changes

2017-05-29 09:24 UTC, bikol requested changes
Ok, travis jest teraz ok. Zostaje merge bo od tego czasu repozytorum sie zmieniło.

2017-05-30 12:31 UTC, m1kra commented
Zmergowane, pull request gotowy.

2017-06-04 19:05 UTC, merged